### ISSUE TITLE
Chaos Worker Jobs Cannot be Activated

### ISSUE THREAD

**Issue by pihme** [zeebe-io/zeebe-cluster-testbench#197]
Recently no chaos worker jobs are being activated with the following error message in the log:

```2021/01/05 09:37:49 Failed to activate jobs for worker zbctl rpc error: code = Unauthenticated desc = Unauthorized: HTTP status code 401; transport: received the unexpected content-type "text/html```

**Comment by Zelldon** [comment]
Might related to https://github.com/zeebe-io/zeebe/issues/5962 or https://github.com/zeebe-io/zeebe/issues/5865

**Comment by Zelldon** [comment]
@pihme could you please save the ~/.camunda/credentials file

**Comment by pihme** [comment]
Overall, this is not a recent phenomenon. It has occurred since December 7th. 
![image](https://user-images.githubusercontent.com/14032870/103632018-067a9780-4f44-11eb-9570-0dc562c1f21b.png)

**Comment by pihme** [comment]
`~/.camunda/credentials`:

```
[REDACTED].zeebe.ultrawombat.com:
  auth:
    credentials:
      accesstoken: [REDACTED]
      tokentype: Bearer
      refreshtoken: ""
      expiry: 2021-01-04T17:02:40.681776667Z
```
